export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headLine:'unlimited transactions with zero fees',
    description: 'consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.png').default,
    alt: 'Camera',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited',
    headLine:'unlimited transactions with zero fees',
    description: 'consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-2.png').default,
    alt: 'Camera',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headLine:'unlimited transactions with zero fees',
    description: 'consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    buttonLabel: 'Start now',
    imgStart: false,
    img: require('../../images/svg-3.png').default,
    alt: 'Camera',
    dark: false,
    primary: false,
    darkText: true,
};