export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Ready to see a different world?',
    headLine:'Our new brand identity shows the expertise and diversity of our people',
    description: ' If you need one security officer or a team of officers, for long term or short term assignments, we can help you!',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.png').default,
    alt: 'Camera',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Prevent Trespassing at a High-rise Residential Community',
    headLine:'Guarding Officers are trained to recognize and prevent unauthorized site activity',
    description: 'Discover how our team used enhanced video surveillance and Remote Perimeter Protection technology to help protect a metropolitan high-rise residential community',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/svg-2.png').default,
    alt: 'Camera',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Careers',
    headLine:'Helping to protect one local client or a large global account',
    description: ' If you are seeking a career that is constantly evolving and full of professional opportunities, join the team.',
    buttonLabel: 'Start now',
    imgStart: false,
    img: require('../../images/svg-3.png').default,
    alt: 'Camera',
    dark: false,
    primary: false,
    darkText: true,
};